spring.application.name=RentKaro

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/rentkaro

# JWT Configuration
jwt.secret=RentKaroSuperSecretKeyForJWTTokenGenerationAndValidation2025SecureKey
jwt.expiration=86400000

# Server Configuration
server.port=8080

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Thymeleaf
spring.thymeleaf.cache=false
